version: "3.8" #docker version
services:
  postgres:
    container_name: dyplom_postgres # use that name as hostname in pgadmin
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: spectator
      POSTGRES_PASSWORD: masterkey
      PGDATA: /var/lib/postgresql/data
    networks:
      - postgresnet
    #comment out if you dont want to externalize the data
    ports:
      - "5433:5432"

  # pgadmin:
  #   container_name: dyplom_pgadmin4
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   networks:
  #     - postgresnet
  #   ports:
  #     - "5050:80"

  pollerserver:
    build:
      context: .
      dockerfile: ./setup/Dockerfile.poller
    container_name: pollerserver
    networks:
      - postgresnet
    volumes:
      - ./poller/logs:/scripts/poller/logs

  backserver:
    build:
      context: .
      dockerfile: ./setup/Dockerfile.symfony
    container_name: backserver
    networks:
      - postgresnet
    ports:
      - "8000:8000"
    depends_on:
      - postgres

networks:
  postgresnet:
    driver: bridge
    ipam:
      config:
        - subnet: "10.251.1.0/24"

volumes:
  postgres:
  pgadmin:
  backserver:
  pollerserver:
