version: "3.8" #docker version
services:
  pollerserver:
    build:
      context: .
      dockerfile: ./poller/Dockerfile
    container_name: pollerserver
    networks:
      - postgres
    volumes:
      - ./poller/logs:/scripts/poller/logs
  postgres:
    container_name: dyplom_postgres # use that name as hostname in pgadmin
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: spectator
      POSTGRES_PASSWORD: masterkey
      PGDATA: /var/lib/postgresql/data
    networks:
      - postgres
    ports:
      - "5433:5432"
  pgadmin:
    container_name: dyplom_pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    networks:
      - postgres
    ports:
      - "5050:80"

networks:
  #connection between two containers
  postgres:
    driver: bridge
    ipam:
      config:
        - subnet: "10.251.1.0/24"

volumes:
  postgres:
  pgadmin:
